Rework Sotw Cache interface
DataDog/go-control-plane pull request #6
Opened 2024-01-10 20:52 UTC by valerian-roche

Datadog fork PR matching https://github.com/envoyproxy/go-control-plane/pull/584

It has been raised that the addition of StreamState within the Cache interface is breaking the separation of concern between the server side managing the xds protocol itself and the cache which is only in charge of returning responses based on watches
PR https://github.com/envoyproxy/go-control-plane/pull/577 has been opened proposing to fully remove any client state from the CreateWatch interface

This PR is an alternate proposal based on a few concerns/aspects:
- one of the argument on removing it is that the sotw protocol is stateless. It actually is not, and is explicitly visible in this PR: the lastResponse latched value as well as the version hack when the resource list is changed very well show that it is stateful
- in cases outside of lds and cds, it is clearly stated that the control-plane is not expected to send back all resources when a single one change. This is highly critical in the case of ads with eds, as there is a likelihood of both having a lot of resources and a high churn. The implementation sending everything each time is technically tolerated, but is pushing on the data-plane work that could be done at low cost on the control-plane
- the current support of both delta and sotw, for both linear and simple cache means that every change has to be done 4 times, with four very different implementations, each one supporting only a subset of use cases (e.g. linear does not support cds/lds as it doesn't handle wildcard in this case, and sotw does not work properly as resource list is improperly maintained). I strongly believed that both implementation should converge. The only remaining differences should be in the messages themselves, abstracted in the server part. Having a common interface for sotw and delta is a first step for this. It would also allow in the future to make snapshot far more efficient by supporting a linear version per snapshot

In this context, this PR is changing:
- creates a ClientState within the cache package, driven by the data needed from the cache perspective to be able to answer a client request
- simplifies streamState
  - makes it compatible with the new ClientState interface
  - removes the IsFirst notion, as the protocol states it should come from the nonce in the request
  - removes the duplicate/parallel knownResourceNames and use the delta one instead. It will also properly carry the version in a future PR

2024-01-16 12:32 UTC, atollena commented on pkg/cache/v3/cache.go
> +type SubscriptionState interface {
Small nit: While the term "stream state" made sense to disambiguate with just "stream", here I think you could get away with just `type Subscription interface`.

2024-01-16 12:32 UTC, atollena commented on pkg/cache/v3/cache.go
> +	GetACKedResources() map[string]string
```suggestion
	AckedResources() map[string]string
```

See https://go.dev/doc/effective_go#Getters.

2024-01-16 12:32 UTC, atollena commented on pkg/cache/v3/cache.go
> +	GetSubscribedResources() map[string]struct{}
```suggestion
	SubscribedResources() map[string]struct{}
```

2024-01-16 12:32 UTC, atollena commented on pkg/cache/v3/cache.go
> +	IsWildcard() bool
Same, could just be `Wildcard() bool`

2024-01-16 12:32 UTC, atollena commented on pkg/cache/v3/linear.go
> +		return nil, fmt.Errorf("request type %s does not match cache type %s", request.TypeUrl, cache.typeURL)
Are there practical cases where this is important to catch this in a production system?

My understanding is that this would be the result of a muxer that is not configured properly, IMO it's not worth increasing the size of the interface for all the valid cases. I'll leave it up to you though.

2024-01-16 12:32 UTC, atollena commented on pkg/cache/v3/mux.go
> +		return nil, fmt.Errorf("no cache defined for key %s", key)
This is quite a big change in behavior, no? Until now if users used a mux cache and a request matched no condition, it would just never get a response, which imo is a valid behavior. Now it gets an error?

2024-01-16 12:32 UTC, atollena commented on pkg/cache/v3/simple_test.go
> +	streamState := stream.NewSubscriptionState(false, map[string]string{})
There are a lot of `var streamState SubscriptionState` remaining. It would be good to clean them up. If you take my suggestion to just call this a `Subscription`, then this will make the code more terse (you can call the vars "sub") while retaining the clarity.

2024-01-16 12:32 UTC, atollena commented on pkg/server/delta/v3/server.go
> +func (s *server) subscribe(resources []string, streamState *stream.SubscriptionState) {
same remark regarding streamState -> subscriptionState (or streamState -> subscription or streamState -> sub), this time for non-test code.

2024-01-16 12:32 UTC, atollena commented on pkg/server/sotw/v3/ads.go
> +			// ToDo: track ACK through subscription state
nit: The project uses `TODO(name)` throughout.

```suggestion
			// TODO(valerian-roche): track ACK through subscription state
```

By the way, isn't this todo what you are doing here at L117? If not, I don't really understand this comment.

2024-01-16 12:32 UTC, atollena commented on pkg/server/sotw/v3/server.go
> +	streamState            map[string]stream.SubscriptionState
fwiw I found the code quite hard to read without the rename of this to something like `subscriptions`. There is Stream, StreamWrapper, StreamState which is actually a SubscriptionState...

2024-01-16 12:32 UTC, atollena commented on pkg/server/sotw/v3/xds.go
> +	if subscriptionState.IsWildcard() && len(req.ResourceNames) == 0 && len(subscriptionState.GetSubscribedResources()) == 0 {
Does that properly handle the case of unsubscribing from explicit wildcard? Probably this is never used, but still I think this violates the protocol spec and should be implemented properly. For example two subsequent requests:

```
Req(resources: ["*"]) -> explicit wildcard subscription -> IsWildcard() = true
...
Req(resources: []) -> IsWilcard = true, req.ResourceName = 0, GetSubscribedResources() == 0, 
```

This will fall into this if statement, even though it should not be considered wildcard and instead should be considered unsubscribing from wildcard.

There seem to be no way to implement the legacy wildcard behavior without storing an additional boolean in what you called `SubscriptionState`:

> For historical reasons, if the client sends a request for a given resource type but has never explicitly subscribed to any resource names

You can't know that without storing whether you've ever seen a resource name on the stream, can you? Without storing this explicitly, there is a high chance that you end up mixing up legacy/implicit and explicit wildcards.

2024-01-16 12:32 UTC, atollena commented on pkg/server/stream/v3/subscription.go
> +// Currently used only when using delta-xds
Is this true? From what I can see this is also used in sotw via updateSubscriptionResources.

2024-01-16 22:41 UTC, valerian-roche commented on pkg/cache/v3/cache.go
> +type SubscriptionState interface {
Agreed, I think it makes sense

2024-01-16 22:43 UTC, valerian-roche commented on pkg/cache/v3/cache.go
> +	GetACKedResources() map[string]string
Updated

2024-01-16 22:43 UTC, valerian-roche commented on pkg/cache/v3/cache.go
> +	GetSubscribedResources() map[string]struct{}
Updated

2024-01-16 22:44 UTC, valerian-roche commented on pkg/cache/v3/cache.go
> +	IsWildcard() bool
Might be my English understanding, but calling "wildcard" makes me more believe it'd be returning something a bit random more than whether it's wildcard. Can update if preferred though

2024-01-16 22:45 UTC, valerian-roche commented on pkg/cache/v3/linear.go
> +		return nil, fmt.Errorf("request type %s does not match cache type %s", request.TypeUrl, cache.typeURL)
We had issues on slack (and I think GitHub) due to such kind of silent errors.

2024-01-16 22:47 UTC, valerian-roche commented on pkg/cache/v3/mux.go
> +		return nil, fmt.Errorf("no cache defined for key %s", key)
In the current case it gets a nil response, which will likely crash in the server implementation side though if I'm not mistaken

2024-01-16 22:48 UTC, valerian-roche commented on pkg/cache/v3/simple_test.go
> +	streamState := stream.NewSubscriptionState(false, map[string]string{})
Good remark, updated

2024-01-16 22:54 UTC, valerian-roche commented on pkg/server/delta/v3/server.go
> +func (s *server) subscribe(resources []string, streamState *stream.SubscriptionState) {
Updated

2024-01-16 23:04 UTC, valerian-roche commented on pkg/server/sotw/v3/ads.go
> +			// ToDo: track ACK through subscription state
Cleaned up, was leftover

2024-01-17 01:31 UTC, valerian-roche commented on pkg/server/sotw/v3/server.go
> +	streamState            map[string]stream.SubscriptionState
I am reworking this part. I believe the watch and the stream state ended up duplicating the same notion

2024-01-17 01:32 UTC, valerian-roche commented on pkg/server/stream/v3/subscription.go
> +// Currently used only when using delta-xds
Nope will update as no longer true

2024-01-17 02:34 UTC, valerian-roche commented on pkg/server/sotw/v3/xds.go
> +	if subscriptionState.IsWildcard() && len(req.ResourceNames) == 0 && len(subscriptionState.GetSubscribedResources()) == 0 {
I agree that we do not support the case when the subscription was explicit wildcard and now requests nothing (not wildcard nor resources). The comment below mentions that we do not support this explicit case currently (in sotw or in delta), but I also don't see much value here. I can add this if preferred though

2024-01-17 09:50 UTC, atollena requested changes

2024-01-17 09:50 UTC, atollena commented on pkg/cache/v3/cache.go
> +	IsWildcard() bool
OK, this one is fine.

2024-01-17 09:50 UTC, atollena commented on pkg/cache/v3/linear.go
> +		return nil, fmt.Errorf("request type %s does not match cache type %s", request.TypeUrl, cache.typeURL)
OK, I'll let you discuss this with other maintainers.

2024-01-17 09:50 UTC, atollena commented on pkg/server/sotw/v3/server.go
> +	streamState            map[string]stream.SubscriptionState
Yes, indeed. Closing this conversation and will re-review that part in https://github.com/DataDog/go-control-plane/pull/7.

2024-01-17 09:51 UTC, atollena commented
I guess you can close this PR.

2024-01-17 09:53 UTC, atollena commented on pkg/cache/v3/mux.go
> +		return nil, fmt.Errorf("no cache defined for key %s", key)
Yes.

2024-01-18 04:22 UTC, closed without merging